# Generated by Django 5.0.3 on 2024-03-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField()),
                ('senha1', models.CharField(max_length=255)),
                ('senha2', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
